### ISSUE TITLE
Security Issue in Nokogiri 

### ISSUE THREAD

**Issue by kristi-sara** [UCSBCarpentry/ucsbcarpentry.github.io#13]
I updated the version from 1.13.3 to the patched 1.13.4 
https://github.com/UCSBCarpentry/ucsbcarpentry.github.io/security/dependabot

**Comment by ilessing** [comment]
I used the same technique for this issue as I did for #11 

```
what I did:
- deleted the file: `Gemfile.lock`
- rebuilt it with `bundle install`

That updated a bunch of dependencies listed in the `Gemfile.lock`

```

**Comment by kristi-sara** [comment]
thanks ian
