### ISSUE TITLE
Re-brand homepage

### ISSUE THREAD

**Issue by jonjab** [UCSBCarpentry/ucsbcarpentry.github.io#3]
We should ditch that Carpentry logo and replace it with a UCSB Library logo of some sort.

The Gaucho Plane? Isla Vista Hand Drill?

**Comment by kristi-sara** [comment]
Are there instruction on how to do this? I wanted to change the birds of paradise pool thing I had up to something else...

**Comment by ilessing** [comment]
see line 6 of file: `index.md` which references a file on the main library website.  
Probably better to put a new image in this repository and and point to it at line 6

**Comment by kristi-sara** [comment]
Thats what I tried to do but the image wouldn't show up. I made a folder (fig) for the image to point at it and I folllowed the syntax and it won't show up.

**Comment by ilessing** [comment]
looks like @jonjab resolved this with b2477915946

@kristi-sara almost had it with 8c8f5c9ad677e

it was the space character between the square brackets and the round brackets.    
![8c8f5c9ad677e](https://user-images.githubusercontent.com/275899/86857755-06244100-c074-11ea-8c2f-cf8af423caf8.png)

Darn computers are so picky.

**Comment by kristi-sara** [comment]
It was actually me adding {{root.page}} before the path. I thought I had to put that in there but I guess not.
