### ISSUE TITLE
navigation links open in a new tab/window

### ISSUE THREAD

**Issue by ilessing** [UCSBCarpentry/ucsbcarpentry.github.io#7]
Navigation links should not open in a new tab.

this can be fixed by eliminating the `target` attribute on `a` links.

example:  

- file: `_layouts/default.html`
- line 31 should look like:

`<li><a href="/past-workshops/">Past Workshops</a></li>`

**Comment by apandas** [comment]
Done! Thanks for showing me how to adjust the nav links
