### ISSUE TITLE
vulnerability in nokuguri

### ISSUE THREAD

**Issue by jonjab** [UCSBCarpentry/ucsbcarpentry.github.io#9]
https://github.com/UCSBCarpentry/ucsbcarpentry.github.io/security/dependabot/1

**Comment by jonjab** [comment]
this was a notification. Ian merged after other auto-notifications.

**Comment by ilessing** [comment]
dependabot fixed with commit 3ae1e217d3 and I merged with commit d57fc8a7aa45
